name: Build and Deploy Quarto Site

on:
  push:
    # branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install local package
      run: |
        cd heading_converter
        pip install -e .
        cd ..
    
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    
    - name: Render Quarto document
      run: |
        quarto render --output-dir docs
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages